### PR TITLE
Updated USGS Data

### PR DESCRIPTION
**Pull request by seperry83**
logic for USGS data:

Some groups (Date/Station) didn't collect nutrient data at all, while some did. Of the ones that did, some collected it at a lower depth than the minimum depth used for temperature, though still within the surface value range (eg. T_min = 0.5 m, nutrients collected at 1 m).

Code first checks if nutrient data was collected for any surface depth in the group; if not, than the surface value w/ the minimum depth is used. If so, it pulls the surface data at the minimum depth that also includes nutrient data.

Logic for bottom nutrients was not included because there was no data for it.

### CODE REVIEW

**Comment by sbashevkin** [comment]
@seperry83 Awesome thanks for this! Would this then also change the depth from which the temperature, salinity, etc. data are being pulled? If the shallowest depth with temperature is 0.5 m but the shallowest for nutrients is 1 m, would it pull all the data from 1m, or pull temp data from 0.5 m and nutrients from 1m?

**Comment by seperry83** [comment]
Yup, it pulls that data from the same depth as the nutrients. I figured that was ideal since it ensures the data is paired/removes the need for multiple depth columns, and it should be okay since 1) the values are still binned as "surface" and 2) usually the difference is only ~1m at most.

**Comment by sbashevkin** [comment]
What is the current distribution of surface sample depths with the way you've written the code? I'm a little concerned about pulling the non-nutrient data from deeper depths since all the other surveys take their surface samples at < 1 m and usually at 1 foot depth. We also have some ongoing work comparing the surface to the bottom temperatures that wouldn't work with this application. 

My preference would be to continue pulling non-nutrient data from the shallowest depth possible, even if it means nutrient data are at a different depth. in this case the sample_depth_surface variable would only apply to the non-nutrient data. If you don't have time to rewrite the code I can tackle it.

**Comment by seperry83** [comment]
Makes sense! From a quick check it seems there's about ~7000 rows where the nutrient depth is deeper than T_min. I can modify the code really quick -- is it worth it to have separate temp/depth/etc. columns associated with the nutrient data (eg. a sample_depth_surface and sample_depth_surface_nutrient column)?

**Comment by sbashevkin** [comment]
If you think it will be helpful I have no problem with adding a sample_depth_surface_nutrient column

**Comment by seperry83** [comment]
Rewrote so that there are now separate Depth/Temp/etc. cols for the baseline data (same col names as before) and for the nutrient data (added _nutr).

**Comment by sbashevkin** [comment]
Sorry I don't think I was clear in my earlier comment. I think we can add an additional nutrient column for the sample depth so we know the specific depth the nutrient data are coming from, but I don't think it makes sense to do so for temperature, salinity, etc., unless there is some reasoning that I'm missing. I think it's OK to have temperature and nutrient data from different depths here. If users want to dig into the weeds of the various sample depths they should probably be using the USGS data directly. 

Would you be OK with removing the Salinity_nutr, Chlorophyll_nutr, and Temperature_nutr columns? Or do you think it's valuable to have these variables from the same depth as the nutrients?

**Comment by seperry83** [comment]
The values between the surface/_nutr depths for temp and salinity do vary a bit, but in the current data the fluctuations are pretty small (max 2 degrees and 15 salinity units, usually less), so I see no harm in removing them.

**Comment by sbashevkin** [comment]
@seperry83 Have you tested this to make sure it's working as intended? I tried removing all the nutrient columns from this version and the last version of the USGS dataset and comparing them with all.equal but there were a number of differences.

**Comment by seperry83** [comment]
I did, but evidently not thoroughly enough; I'll look into it.

**Comment by sbashevkin** [comment]
Ok thanks! I also noticed that "surface" was removed from the sample depth column names so I added that back in.

**Comment by seperry83** [comment]
Good news, it wasn't a data issue -- I added a line to reset the index after joining all the datasets together to keep things tidy, but I removed it so it's easier to compare to the old commits.

Once that's removed, all.equal says "Length mismatch: comparison on first 12 components" when compared to the current commit (seems to be just some very technical differences in the encoding) and "TRUE" when I compared the data to that from two versions ago (hash 57afcd27ff).

**Pull request merged**
